services:
  auth:
    env_file:
    - ../env/common.env
    - ../env/auth.env
    ports:
    - 8000:8000
    networks:
    - sibu-net
    image: ${DOCKERHUB_USER:-jccasav}/sibu-auth:${SIBU_TAG:-qa}
    pull_policy: if_not_present
networks:
  sibu-net:
    name: sibu-net
    external: true
